### ISSUE TITLE
Pending Issues

### ISSUE THREAD

**Issue by codechennai** [codechennnai/site#2]
- HTML5 is not displaying in list still in colleges tab
- Change courses tab color and card style
- Set a color for hyperlinks 'here'
- Home page font find if any better font for Code Chennai

**Comment by AsathalMannan** [comment]
**HTML5 is already in the list...** @codechennai  

![image](https://cloud.githubusercontent.com/assets/10103859/25442848/c5d831fe-2ac3-11e7-8941-8fa378456dd8.png)
